// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// APILogsColumns holds the columns for the "api_logs" table.
	APILogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// APILogsTable holds the schema information for the "api_logs" table.
	APILogsTable = &schema.Table{
		Name:       "api_logs",
		Columns:    APILogsColumns,
		PrimaryKey: []*schema.Column{APILogsColumns[0]},
	}
	// GinLogsColumns holds the columns for the "gin_logs" table.
	GinLogsColumns = []*schema.Column{
		{Name: "request_id", Type: field.TypeInt64, Increment: true},
		{Name: "request_time", Type: field.TypeTime, Nullable: true},
		{Name: "request_host", Type: field.TypeString, Nullable: true},
		{Name: "request_path", Type: field.TypeString, Nullable: true},
		{Name: "request_query", Type: field.TypeString, Nullable: true},
		{Name: "request_method", Type: field.TypeString, Nullable: true},
		{Name: "request_scheme", Type: field.TypeString, Nullable: true},
		{Name: "request_content_type", Type: field.TypeString, Nullable: true},
		{Name: "request_body", Type: field.TypeString, Nullable: true},
		{Name: "request_client_ip", Type: field.TypeString, Nullable: true},
		{Name: "request_user_agent", Type: field.TypeString, Nullable: true},
		{Name: "request_header", Type: field.TypeString, Nullable: true},
		{Name: "request_cost_time", Type: field.TypeInt64, Nullable: true},
		{Name: "response_time", Type: field.TypeTime, Nullable: true},
		{Name: "response_header", Type: field.TypeString, Nullable: true},
		{Name: "response_status_code", Type: field.TypeInt, Nullable: true},
		{Name: "response_data", Type: field.TypeString, Nullable: true},
		{Name: "go_version", Type: field.TypeString, Nullable: true},
		{Name: "sdk_version", Type: field.TypeString, Nullable: true},
		{Name: "system_info", Type: field.TypeString, Nullable: true},
	}
	// GinLogsTable holds the schema information for the "gin_logs" table.
	GinLogsTable = &schema.Table{
		Name:       "gin_logs",
		Columns:    GinLogsColumns,
		PrimaryKey: []*schema.Column{GinLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "ginlog_request_time",
				Unique:  false,
				Columns: []*schema.Column{GinLogsColumns[1]},
			},
			{
				Name:    "ginlog_request_path",
				Unique:  false,
				Columns: []*schema.Column{GinLogsColumns[3]},
			},
			{
				Name:    "ginlog_request_method",
				Unique:  false,
				Columns: []*schema.Column{GinLogsColumns[5]},
			},
		},
	}
	// HertzlogsColumns holds the columns for the "hertzlogs" table.
	HertzlogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// HertzlogsTable holds the schema information for the "hertzlogs" table.
	HertzlogsTable = &schema.Table{
		Name:       "hertzlogs",
		Columns:    HertzlogsColumns,
		PrimaryKey: []*schema.Column{HertzlogsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		APILogsTable,
		GinLogsTable,
		HertzlogsTable,
	}
)

func init() {
}
