// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"go.dtapp.net/golog/internal/ent/apilog"
	"go.dtapp.net/golog/internal/ent/predicate"
)

// ApiLogQuery is the builder for querying ApiLog entities.
type ApiLogQuery struct {
	config
	ctx        *QueryContext
	order      []apilog.OrderOption
	inters     []Interceptor
	predicates []predicate.ApiLog
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ApiLogQuery builder.
func (alq *ApiLogQuery) Where(ps ...predicate.ApiLog) *ApiLogQuery {
	alq.predicates = append(alq.predicates, ps...)
	return alq
}

// Limit the number of records to be returned by this query.
func (alq *ApiLogQuery) Limit(limit int) *ApiLogQuery {
	alq.ctx.Limit = &limit
	return alq
}

// Offset to start from.
func (alq *ApiLogQuery) Offset(offset int) *ApiLogQuery {
	alq.ctx.Offset = &offset
	return alq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (alq *ApiLogQuery) Unique(unique bool) *ApiLogQuery {
	alq.ctx.Unique = &unique
	return alq
}

// Order specifies how the records should be ordered.
func (alq *ApiLogQuery) Order(o ...apilog.OrderOption) *ApiLogQuery {
	alq.order = append(alq.order, o...)
	return alq
}

// First returns the first ApiLog entity from the query.
// Returns a *NotFoundError when no ApiLog was found.
func (alq *ApiLogQuery) First(ctx context.Context) (*ApiLog, error) {
	nodes, err := alq.Limit(1).All(setContextOp(ctx, alq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{apilog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (alq *ApiLogQuery) FirstX(ctx context.Context) *ApiLog {
	node, err := alq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ApiLog ID from the query.
// Returns a *NotFoundError when no ApiLog ID was found.
func (alq *ApiLogQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = alq.Limit(1).IDs(setContextOp(ctx, alq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{apilog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (alq *ApiLogQuery) FirstIDX(ctx context.Context) int {
	id, err := alq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ApiLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ApiLog entity is found.
// Returns a *NotFoundError when no ApiLog entities are found.
func (alq *ApiLogQuery) Only(ctx context.Context) (*ApiLog, error) {
	nodes, err := alq.Limit(2).All(setContextOp(ctx, alq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{apilog.Label}
	default:
		return nil, &NotSingularError{apilog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (alq *ApiLogQuery) OnlyX(ctx context.Context) *ApiLog {
	node, err := alq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ApiLog ID in the query.
// Returns a *NotSingularError when more than one ApiLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (alq *ApiLogQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = alq.Limit(2).IDs(setContextOp(ctx, alq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{apilog.Label}
	default:
		err = &NotSingularError{apilog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (alq *ApiLogQuery) OnlyIDX(ctx context.Context) int {
	id, err := alq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ApiLogs.
func (alq *ApiLogQuery) All(ctx context.Context) ([]*ApiLog, error) {
	ctx = setContextOp(ctx, alq.ctx, "All")
	if err := alq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ApiLog, *ApiLogQuery]()
	return withInterceptors[[]*ApiLog](ctx, alq, qr, alq.inters)
}

// AllX is like All, but panics if an error occurs.
func (alq *ApiLogQuery) AllX(ctx context.Context) []*ApiLog {
	nodes, err := alq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ApiLog IDs.
func (alq *ApiLogQuery) IDs(ctx context.Context) (ids []int, err error) {
	if alq.ctx.Unique == nil && alq.path != nil {
		alq.Unique(true)
	}
	ctx = setContextOp(ctx, alq.ctx, "IDs")
	if err = alq.Select(apilog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (alq *ApiLogQuery) IDsX(ctx context.Context) []int {
	ids, err := alq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (alq *ApiLogQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, alq.ctx, "Count")
	if err := alq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, alq, querierCount[*ApiLogQuery](), alq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (alq *ApiLogQuery) CountX(ctx context.Context) int {
	count, err := alq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (alq *ApiLogQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, alq.ctx, "Exist")
	switch _, err := alq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (alq *ApiLogQuery) ExistX(ctx context.Context) bool {
	exist, err := alq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ApiLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (alq *ApiLogQuery) Clone() *ApiLogQuery {
	if alq == nil {
		return nil
	}
	return &ApiLogQuery{
		config:     alq.config,
		ctx:        alq.ctx.Clone(),
		order:      append([]apilog.OrderOption{}, alq.order...),
		inters:     append([]Interceptor{}, alq.inters...),
		predicates: append([]predicate.ApiLog{}, alq.predicates...),
		// clone intermediate query.
		sql:  alq.sql.Clone(),
		path: alq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (alq *ApiLogQuery) GroupBy(field string, fields ...string) *ApiLogGroupBy {
	alq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ApiLogGroupBy{build: alq}
	grbuild.flds = &alq.ctx.Fields
	grbuild.label = apilog.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (alq *ApiLogQuery) Select(fields ...string) *ApiLogSelect {
	alq.ctx.Fields = append(alq.ctx.Fields, fields...)
	sbuild := &ApiLogSelect{ApiLogQuery: alq}
	sbuild.label = apilog.Label
	sbuild.flds, sbuild.scan = &alq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ApiLogSelect configured with the given aggregations.
func (alq *ApiLogQuery) Aggregate(fns ...AggregateFunc) *ApiLogSelect {
	return alq.Select().Aggregate(fns...)
}

func (alq *ApiLogQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range alq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, alq); err != nil {
				return err
			}
		}
	}
	for _, f := range alq.ctx.Fields {
		if !apilog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if alq.path != nil {
		prev, err := alq.path(ctx)
		if err != nil {
			return err
		}
		alq.sql = prev
	}
	return nil
}

func (alq *ApiLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ApiLog, error) {
	var (
		nodes = []*ApiLog{}
		_spec = alq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ApiLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ApiLog{config: alq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, alq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (alq *ApiLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := alq.querySpec()
	_spec.Node.Columns = alq.ctx.Fields
	if len(alq.ctx.Fields) > 0 {
		_spec.Unique = alq.ctx.Unique != nil && *alq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, alq.driver, _spec)
}

func (alq *ApiLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(apilog.Table, apilog.Columns, sqlgraph.NewFieldSpec(apilog.FieldID, field.TypeInt))
	_spec.From = alq.sql
	if unique := alq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if alq.path != nil {
		_spec.Unique = true
	}
	if fields := alq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apilog.FieldID)
		for i := range fields {
			if fields[i] != apilog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := alq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := alq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := alq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := alq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (alq *ApiLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(alq.driver.Dialect())
	t1 := builder.Table(apilog.Table)
	columns := alq.ctx.Fields
	if len(columns) == 0 {
		columns = apilog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if alq.sql != nil {
		selector = alq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if alq.ctx.Unique != nil && *alq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range alq.predicates {
		p(selector)
	}
	for _, p := range alq.order {
		p(selector)
	}
	if offset := alq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := alq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ApiLogGroupBy is the group-by builder for ApiLog entities.
type ApiLogGroupBy struct {
	selector
	build *ApiLogQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (algb *ApiLogGroupBy) Aggregate(fns ...AggregateFunc) *ApiLogGroupBy {
	algb.fns = append(algb.fns, fns...)
	return algb
}

// Scan applies the selector query and scans the result into the given value.
func (algb *ApiLogGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, algb.build.ctx, "GroupBy")
	if err := algb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ApiLogQuery, *ApiLogGroupBy](ctx, algb.build, algb, algb.build.inters, v)
}

func (algb *ApiLogGroupBy) sqlScan(ctx context.Context, root *ApiLogQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(algb.fns))
	for _, fn := range algb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*algb.flds)+len(algb.fns))
		for _, f := range *algb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*algb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := algb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ApiLogSelect is the builder for selecting fields of ApiLog entities.
type ApiLogSelect struct {
	*ApiLogQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (als *ApiLogSelect) Aggregate(fns ...AggregateFunc) *ApiLogSelect {
	als.fns = append(als.fns, fns...)
	return als
}

// Scan applies the selector query and scans the result into the given value.
func (als *ApiLogSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, als.ctx, "Select")
	if err := als.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ApiLogQuery, *ApiLogSelect](ctx, als.ApiLogQuery, als, als.inters, v)
}

func (als *ApiLogSelect) sqlScan(ctx context.Context, root *ApiLogQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(als.fns))
	for _, fn := range als.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*als.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := als.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
