// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"go.dtapp.net/golog/internal/ent/apilog"
)

// ApiLog is the model entity for the ApiLog schema.
type ApiLog struct {
	config
	// ID of the ent.
	ID           int `json:"id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ApiLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case apilog.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ApiLog fields.
func (al *ApiLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case apilog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			al.ID = int(value.Int64)
		default:
			al.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ApiLog.
// This includes values selected through modifiers, order, etc.
func (al *ApiLog) Value(name string) (ent.Value, error) {
	return al.selectValues.Get(name)
}

// Update returns a builder for updating this ApiLog.
// Note that you need to call ApiLog.Unwrap() before calling this method if this ApiLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (al *ApiLog) Update() *ApiLogUpdateOne {
	return NewApiLogClient(al.config).UpdateOne(al)
}

// Unwrap unwraps the ApiLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (al *ApiLog) Unwrap() *ApiLog {
	_tx, ok := al.config.driver.(*txDriver)
	if !ok {
		panic("ent: ApiLog is not a transactional entity")
	}
	al.config.driver = _tx.drv
	return al
}

// String implements the fmt.Stringer.
func (al *ApiLog) String() string {
	var builder strings.Builder
	builder.WriteString("ApiLog(")
	builder.WriteString(fmt.Sprintf("id=%v", al.ID))
	builder.WriteByte(')')
	return builder.String()
}

// ApiLogs is a parsable slice of ApiLog.
type ApiLogs []*ApiLog
