// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"go.dtapp.net/golog/internal/ent/ginlog"
	"go.dtapp.net/golog/internal/ent/predicate"
)

// GinLogDelete is the builder for deleting a GinLog entity.
type GinLogDelete struct {
	config
	hooks    []Hook
	mutation *GinLogMutation
}

// Where appends a list predicates to the GinLogDelete builder.
func (gld *GinLogDelete) Where(ps ...predicate.GinLog) *GinLogDelete {
	gld.mutation.Where(ps...)
	return gld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (gld *GinLogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, gld.sqlExec, gld.mutation, gld.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (gld *GinLogDelete) ExecX(ctx context.Context) int {
	n, err := gld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (gld *GinLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(ginlog.Table, sqlgraph.NewFieldSpec(ginlog.FieldID, field.TypeInt64))
	if ps := gld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, gld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	gld.mutation.done = true
	return affected, err
}

// GinLogDeleteOne is the builder for deleting a single GinLog entity.
type GinLogDeleteOne struct {
	gld *GinLogDelete
}

// Where appends a list predicates to the GinLogDelete builder.
func (gldo *GinLogDeleteOne) Where(ps ...predicate.GinLog) *GinLogDeleteOne {
	gldo.gld.mutation.Where(ps...)
	return gldo
}

// Exec executes the deletion query.
func (gldo *GinLogDeleteOne) Exec(ctx context.Context) error {
	n, err := gldo.gld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{ginlog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (gldo *GinLogDeleteOne) ExecX(ctx context.Context) {
	if err := gldo.Exec(ctx); err != nil {
		panic(err)
	}
}
