// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"go.dtapp.net/golog/internal/ent/hertzlog"
)

// Hertzlog is the model entity for the Hertzlog schema.
type Hertzlog struct {
	config
	// ID of the ent.
	ID           int `json:"id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Hertzlog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case hertzlog.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Hertzlog fields.
func (h *Hertzlog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case hertzlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			h.ID = int(value.Int64)
		default:
			h.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Hertzlog.
// This includes values selected through modifiers, order, etc.
func (h *Hertzlog) Value(name string) (ent.Value, error) {
	return h.selectValues.Get(name)
}

// Update returns a builder for updating this Hertzlog.
// Note that you need to call Hertzlog.Unwrap() before calling this method if this Hertzlog
// was returned from a transaction, and the transaction was committed or rolled back.
func (h *Hertzlog) Update() *HertzlogUpdateOne {
	return NewHertzlogClient(h.config).UpdateOne(h)
}

// Unwrap unwraps the Hertzlog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (h *Hertzlog) Unwrap() *Hertzlog {
	_tx, ok := h.config.driver.(*txDriver)
	if !ok {
		panic("ent: Hertzlog is not a transactional entity")
	}
	h.config.driver = _tx.drv
	return h
}

// String implements the fmt.Stringer.
func (h *Hertzlog) String() string {
	var builder strings.Builder
	builder.WriteString("Hertzlog(")
	builder.WriteString(fmt.Sprintf("id=%v", h.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Hertzlogs is a parsable slice of Hertzlog.
type Hertzlogs []*Hertzlog
