// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"go.dtapp.net/golog/internal/ent/hertzlog"
	"go.dtapp.net/golog/internal/ent/predicate"
)

// HertzlogUpdate is the builder for updating Hertzlog entities.
type HertzlogUpdate struct {
	config
	hooks    []Hook
	mutation *HertzlogMutation
}

// Where appends a list predicates to the HertzlogUpdate builder.
func (hu *HertzlogUpdate) Where(ps ...predicate.Hertzlog) *HertzlogUpdate {
	hu.mutation.Where(ps...)
	return hu
}

// Mutation returns the HertzlogMutation object of the builder.
func (hu *HertzlogUpdate) Mutation() *HertzlogMutation {
	return hu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (hu *HertzlogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, hu.sqlSave, hu.mutation, hu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (hu *HertzlogUpdate) SaveX(ctx context.Context) int {
	affected, err := hu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (hu *HertzlogUpdate) Exec(ctx context.Context) error {
	_, err := hu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hu *HertzlogUpdate) ExecX(ctx context.Context) {
	if err := hu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (hu *HertzlogUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(hertzlog.Table, hertzlog.Columns, sqlgraph.NewFieldSpec(hertzlog.FieldID, field.TypeInt))
	if ps := hu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, hu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hertzlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	hu.mutation.done = true
	return n, nil
}

// HertzlogUpdateOne is the builder for updating a single Hertzlog entity.
type HertzlogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HertzlogMutation
}

// Mutation returns the HertzlogMutation object of the builder.
func (huo *HertzlogUpdateOne) Mutation() *HertzlogMutation {
	return huo.mutation
}

// Where appends a list predicates to the HertzlogUpdate builder.
func (huo *HertzlogUpdateOne) Where(ps ...predicate.Hertzlog) *HertzlogUpdateOne {
	huo.mutation.Where(ps...)
	return huo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (huo *HertzlogUpdateOne) Select(field string, fields ...string) *HertzlogUpdateOne {
	huo.fields = append([]string{field}, fields...)
	return huo
}

// Save executes the query and returns the updated Hertzlog entity.
func (huo *HertzlogUpdateOne) Save(ctx context.Context) (*Hertzlog, error) {
	return withHooks(ctx, huo.sqlSave, huo.mutation, huo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (huo *HertzlogUpdateOne) SaveX(ctx context.Context) *Hertzlog {
	node, err := huo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (huo *HertzlogUpdateOne) Exec(ctx context.Context) error {
	_, err := huo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (huo *HertzlogUpdateOne) ExecX(ctx context.Context) {
	if err := huo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (huo *HertzlogUpdateOne) sqlSave(ctx context.Context) (_node *Hertzlog, err error) {
	_spec := sqlgraph.NewUpdateSpec(hertzlog.Table, hertzlog.Columns, sqlgraph.NewFieldSpec(hertzlog.FieldID, field.TypeInt))
	id, ok := huo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Hertzlog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := huo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hertzlog.FieldID)
		for _, f := range fields {
			if !hertzlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != hertzlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := huo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &Hertzlog{config: huo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, huo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hertzlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	huo.mutation.done = true
	return _node, nil
}
