// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ApiLog is the predicate function for apilog builders.
type ApiLog func(*sql.Selector)

// GinLog is the predicate function for ginlog builders.
type GinLog func(*sql.Selector)

// Hertzlog is the predicate function for hertzlog builders.
type Hertzlog func(*sql.Selector)
